### ISSUE TITLE
status does not change

### ISSUE THREAD

**Issue by zeroprime790** [iqwunder/pihole_status#1]
I followed the guide step by step but when i'm flipping the switch it seems to turn off. Although when i'm getting back to the switch the status is on. Can you help me debug this issue?

**Comment by iqwunder** [comment]
Hi.
I will try to help you.
When API Url und Code are wrong, it will show an error message, so i think the api extension on the server can be received.

**Check Path to status script:**

The pihole_status.sh is expected in the following path:
$statusScript = "/usr/local/bin/pihole_status.sh";
it should be executable (chmod +x ...)
Also the sudoers entry should exist.

When turning pihole off, the gravity.list will be renamed. it should be in following location:
$gravityList = "/etc/pihole/gravity.list";

you can start the pihole_status.sh on the server to view the logs. it will rename the gravity.list.

**Query the status:**

You can query the status via browser if you give in following url:
_http://192.168.178.1/api/apiext.php?piholekey=123456789&action=status_
You have to change the url and pihole-key to your own settings.

The result should look like this (important ist state):
**Active:**
{"success":true,"state":true,"message":"Pi-Hole is active","action":"status"}
**Inactive:**
{"success":true,"state":false,"message":"Pi-Hole is active","action":"status"}

I hope this hints will help you debugging this issue.
